# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/igor/Work/misc/cyphal_ws/types/public_regulated_data_types/uavcan/primitive/scalar/Integer8.1.0.dsdl
#
# Generated at:  2025-12-16 13:33:59.349460 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     uavcan.primitive.scalar.Integer8
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class Integer8_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 value: None | int | _np_.int8 = None) -> None:
        """
        uavcan.primitive.scalar.Integer8.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param value: saturated int8 value
        """
        self._value: int

        self.value = value if value is not None else 0  # type: ignore

    @property
    def value(self) -> int:
        """
        saturated int8 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: int | _np_.int8) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if -128 <= x <= 127:
            self._value = x
        else:
            raise ValueError(f'value: value {x} is not in [-128, 127]')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_i8(max(min(self.value, 127), -128))
        _ser_.pad_to_alignment(8)
        assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
            'Bad serialization of uavcan.primitive.scalar.Integer8.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> Integer8_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "value"
        _f0_ = _des_.fetch_aligned_i8()
        self = Integer8_1_0(
            value=_f0_)
        _des_.pad_to_alignment(8)
        assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
            'Bad deserialization of uavcan.primitive.scalar.Integer8.1.0'
        assert isinstance(self, Integer8_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'value=%s' % self.value,
        ])
        return f'uavcan.primitive.scalar.Integer8.1.0({_o_0_})'

    _EXTENT_BYTES_ = 1

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8$6rBd0{^X3&1)1f6kl<-t*ur|iyo~Wq<Waqn@3R;Wo^4yKTZ;oN!)~HCLtf|u28TC#X>-#&;Qq#op!fYdUG$E@Fws5zTVgF'
        '@7-=^`b)R%gnO<F;)PRGt1pykQIN{i)_4^Jq-%S@#VSN6-cGE5W4M0^2e6fTq@gv|HzOTYv?;7pwF+t^3SUu8UGb_3Vkq2WNK0fS'
        'oL8m+*-4A<PtM2Cztr!1heJp!gofZ0i$Qq!2p6H6eFUlZLJ7_1XqE}5fs&9RUi5s15YpP78a9HTK>VB73SlY`Et+AF&|kvV74?DC'
        'h6|7z>E__HO@3B9!`gN(A)U@QcmrvJ_&^&@9Y5RXM`W^>dLybM&hHX#Do7oOjHdN7><OE+x*mYslxrT*aABROXb>EZ(kl6+#)1=T'
        'Tp)_WPFf@0L{|wcXhAH+S!p%@X~hbn4VnSz$^hLQ4|4Gs(ti04mGPw-8drWWZojORugYp-CDr7!FSCrkw2^655hsRG=kariec75`'
        '&Lk~c)5}xSi$}%7BAWnHP1cE|9>F=$gzU;lRRWIW9eFq1nDT8C*I+pZU@I-O0}%Nc*B06#7^qpcM7lNQOoAcKm@sYTEyecoL3;VW'
        'h_)=cglP}y-f6t%_9CZn{toHtQx#rM?|XPX30S&JjK#INsEMD{%pe>TZClg^!y9m0cCBzU7&njU0;#0J6_8KT^#SEvHN$^ClFxH>'
        'Cu&q}a=wZk+BE)zt^U$4&u~v|+X!PH8Pcs)lQ#elbes>1c?(dZ{Cb&)v8By)m3JcZEVAMc!d9|oS_A+9'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
