# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2024-06-20 11:16:14.677176 UTC
# Namespace:     uavcan.si.sample.duration

from uavcan.si.sample.duration.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.sample.duration.WideScalar_1_0 import WideScalar_1_0 as WideScalar_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
WideScalar_1 = WideScalar_1_0
