# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/igor/Work/misc/cyphal_ws/types/public_regulated_data_types/reg/udral/service/actuator/common/FaultFlags.0.1.dsdl
#
# Generated at:  2025-12-16 13:33:59.608584 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.service.actuator.common.FaultFlags
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class FaultFlags_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 overload:               None | bool = None,
                 voltage:                None | bool = None,
                 motor_temperature:      None | bool = None,
                 controller_temperature: None | bool = None,
                 velocity:               None | bool = None,
                 mechanical:             None | bool = None,
                 vibration:              None | bool = None,
                 configuration:          None | bool = None,
                 control_mode:           None | bool = None,
                 other:                  None | bool = None) -> None:
        """
        reg.udral.service.actuator.common.FaultFlags.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param overload:               saturated bool overload
        :param voltage:                saturated bool voltage
        :param motor_temperature:      saturated bool motor_temperature
        :param controller_temperature: saturated bool controller_temperature
        :param velocity:               saturated bool velocity
        :param mechanical:             saturated bool mechanical
        :param vibration:              saturated bool vibration
        :param configuration:          saturated bool configuration
        :param control_mode:           saturated bool control_mode
        :param other:                  saturated bool other
        """
        self._overload:               bool
        self._voltage:                bool
        self._motor_temperature:      bool
        self._controller_temperature: bool
        self._velocity:               bool
        self._mechanical:             bool
        self._vibration:              bool
        self._configuration:          bool
        self._control_mode:           bool
        self._other:                  bool

        self.overload = overload if overload is not None else False

        self.voltage = voltage if voltage is not None else False

        self.motor_temperature = motor_temperature if motor_temperature is not None else False

        self.controller_temperature = controller_temperature if controller_temperature is not None else False

        self.velocity = velocity if velocity is not None else False

        self.mechanical = mechanical if mechanical is not None else False

        self.vibration = vibration if vibration is not None else False

        self.configuration = configuration if configuration is not None else False

        self.control_mode = control_mode if control_mode is not None else False

        self.other = other if other is not None else False

    @property
    def overload(self) -> bool:
        """
        saturated bool overload
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._overload

    @overload.setter
    def overload(self, x: bool) -> None:
        self._overload = bool(x)  # Cast to bool implements saturation

    @property
    def voltage(self) -> bool:
        """
        saturated bool voltage
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._voltage

    @voltage.setter
    def voltage(self, x: bool) -> None:
        self._voltage = bool(x)  # Cast to bool implements saturation

    @property
    def motor_temperature(self) -> bool:
        """
        saturated bool motor_temperature
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._motor_temperature

    @motor_temperature.setter
    def motor_temperature(self, x: bool) -> None:
        self._motor_temperature = bool(x)  # Cast to bool implements saturation

    @property
    def controller_temperature(self) -> bool:
        """
        saturated bool controller_temperature
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._controller_temperature

    @controller_temperature.setter
    def controller_temperature(self, x: bool) -> None:
        self._controller_temperature = bool(x)  # Cast to bool implements saturation

    @property
    def velocity(self) -> bool:
        """
        saturated bool velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._velocity

    @velocity.setter
    def velocity(self, x: bool) -> None:
        self._velocity = bool(x)  # Cast to bool implements saturation

    @property
    def mechanical(self) -> bool:
        """
        saturated bool mechanical
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._mechanical

    @mechanical.setter
    def mechanical(self, x: bool) -> None:
        self._mechanical = bool(x)  # Cast to bool implements saturation

    @property
    def vibration(self) -> bool:
        """
        saturated bool vibration
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._vibration

    @vibration.setter
    def vibration(self, x: bool) -> None:
        self._vibration = bool(x)  # Cast to bool implements saturation

    @property
    def configuration(self) -> bool:
        """
        saturated bool configuration
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._configuration

    @configuration.setter
    def configuration(self, x: bool) -> None:
        self._configuration = bool(x)  # Cast to bool implements saturation

    @property
    def control_mode(self) -> bool:
        """
        saturated bool control_mode
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._control_mode

    @control_mode.setter
    def control_mode(self, x: bool) -> None:
        self._control_mode = bool(x)  # Cast to bool implements saturation

    @property
    def other(self) -> bool:
        """
        saturated bool other
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._other

    @other.setter
    def other(self, x: bool) -> None:
        self._other = bool(x)  # Cast to bool implements saturation

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_unaligned_bit(self.overload)
        _ser_.add_unaligned_bit(self.voltage)
        _ser_.add_unaligned_bit(self.motor_temperature)
        _ser_.add_unaligned_bit(self.controller_temperature)
        _ser_.add_unaligned_bit(self.velocity)
        _ser_.add_unaligned_bit(self.mechanical)
        _ser_.add_unaligned_bit(self.vibration)
        _ser_.add_unaligned_bit(self.configuration)
        _ser_.add_unaligned_bit(self.control_mode)
        _ser_.skip_bits(6)
        _ser_.add_unaligned_bit(self.other)
        _ser_.pad_to_alignment(8)
        assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
            'Bad serialization of reg.udral.service.actuator.common.FaultFlags.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> FaultFlags_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "overload"
        _f0_ = _des_.fetch_unaligned_bit()
        # Temporary _f1_ holds the value of "voltage"
        _f1_ = _des_.fetch_unaligned_bit()
        # Temporary _f2_ holds the value of "motor_temperature"
        _f2_ = _des_.fetch_unaligned_bit()
        # Temporary _f3_ holds the value of "controller_temperature"
        _f3_ = _des_.fetch_unaligned_bit()
        # Temporary _f4_ holds the value of "velocity"
        _f4_ = _des_.fetch_unaligned_bit()
        # Temporary _f5_ holds the value of "mechanical"
        _f5_ = _des_.fetch_unaligned_bit()
        # Temporary _f6_ holds the value of "vibration"
        _f6_ = _des_.fetch_unaligned_bit()
        # Temporary _f7_ holds the value of "configuration"
        _f7_ = _des_.fetch_unaligned_bit()
        # Temporary _f8_ holds the value of "control_mode"
        _f8_ = _des_.fetch_unaligned_bit()
        # Temporary _f9_ holds the value of ""
        _des_.skip_bits(6)
        # Temporary _f10_ holds the value of "other"
        _f10_ = _des_.fetch_unaligned_bit()
        self = FaultFlags_0_1(
            overload=_f0_,
            voltage=_f1_,
            motor_temperature=_f2_,
            controller_temperature=_f3_,
            velocity=_f4_,
            mechanical=_f5_,
            vibration=_f6_,
            configuration=_f7_,
            control_mode=_f8_,
            other=_f10_)
        _des_.pad_to_alignment(8)
        assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
            'Bad deserialization of reg.udral.service.actuator.common.FaultFlags.0.1'
        assert isinstance(self, FaultFlags_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'overload=%s' % self.overload,
            'voltage=%s' % self.voltage,
            'motor_temperature=%s' % self.motor_temperature,
            'controller_temperature=%s' % self.controller_temperature,
            'velocity=%s' % self.velocity,
            'mechanical=%s' % self.mechanical,
            'vibration=%s' % self.vibration,
            'configuration=%s' % self.configuration,
            'control_mode=%s' % self.control_mode,
            'other=%s' % self.other,
        ])
        return f'reg.udral.service.actuator.common.FaultFlags.0.1({_o_0_})'

    _EXTENT_BYTES_ = 2

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8$6rBd0{`t+ZEqYk5Kc&PxukEYQi|vY>IhU4soez?kf2B?ty+YxNmG&*K7fpO*LSw+T`#uxl0!nG6)%cpsfe0CiG+Cl0gQL='
        'Ew@)G1;i&JMYn6u^UQeWnel!#|KlI0X39T%G4CZh5dqdzaU%E^BoZ{hu}pKRxuMRU+BK?(O`+&sFQ@K_+j!`{bnA8jXC#IF%Zhe_'
        'B2h#Hz|rL~4G5SMBUJ!2smy{~q!8woARX;&6L+c7TxO2V*v0$(=O?Z;)0+L(J#_X2CdMcp6^3f}DL8sch(jx97jAJXl2K^OI3b2$'
        '<KulAJXbvBhIhf@#C0hJCE3yQoxl+{SkSCvm}|`fX-u@isZ6M2=j{2N0fC1FH(+neZ~2pa<34ou9M*<p2~o*7(P0s>1>2O61R+V{'
        '>^x3n?CcwRj3U2+xJD#`eYAUL6G??2y)>hW7|0WfsF3@}uyQwWK(<na%U0R>{?m)CS$2WF#4c987Q0dy(t)7Y?8a`9=c0%DOCw+4'
        '=WkG-O(j$r8=B@mK#+)cGIK2K`B-K~Ng-&B;L_gc{hx-|>;fj{rss*T`XrM`O98S$gB>K>CFjxXKa-c`l*Wu?JSM{Xd23kAm}HqW'
        '5I9N{NF_r_0n`!^G(w;@;R23&JXcFy9#vxSo<i?wjB2=v1cmb<dJt2Z=x004DJV^wcZ!jlS8j~2_#~xVYo2v{Re08gwn~o2eX?Kn'
        'ejlybcl`+z{k)*sP)Jy{jr_Lv<Flthv{L!qs8^n3IA6TW)Ar;JNfHR==oDb9_QLem?@A7h*Srru<1G)NHZ;V@0=CA2;~Zu|LNuyO'
        '(6-FzKuDE<)}h>qR9AFPW8UWRhL4uo)v@u0qh2*cJvU-!*{kejc7<)Qt1M)1vp3m$>>9htHd%|k&+f7<_8I%6fWef|T+x_7M%<x2'
        'jobWyCfKJ4!@;)gS*&HDVhS6A;+(+Pv8Vly;8B1<^q^9^v;*_~V8?Ghadtnv2RYIq??@GXB-Miu3LJ-VFK0yHeI5E)s>8g91dlO{'
        'q(XT2qdBWXSPaW+AnacQ;h;=mbq$20Yan<ncs=l?apkC7#f)eORME`fKH43!wU6)3&dh9rCSXd$rSc%d2{q6!AcnT5Lv7Co8caa{'
        '#w#*c5~`ePZwRQ7YWl?9pvx1gg5}LI4lg!M4cceWrQST2N>QE5EGb!uf<hUphAqVn07x6EUd}3S1P35!9r|no5%0gvvyuBs4%e17'
        'rHC1m>vzJCX2Cvxz;l{#5=hkv{ad&Tta!+ZJuAejVWM~+FrW-{H{3VKYi=y|%SVpMC=rGs&14}G)Sp7zceXy*-n<<+yHYBzy67{='
        'dv({&K^5UXE$is);-D6`IjE(xjjEc?E{|R7)V@#(4I7D-l%^!tIRPx=_U6B$u1YKOI1=y~acR)nqq`N9V<z97J$ap*+vWQ%y!Kn&'
        '&Ov^iMNcEqy)=>#3rKT|rV<8+SKpnoB#?vQH$nr)jKj=fkL;QL5ULrm@7UMFr$_dA7^S{-v#FGJsbYjq@bwr&9!_C<T+OW?{<r*Z'
        'ETPKVg%CvbYISR1xC9I89=r9{?Dsl?@7%l+1bjOd5y&>>ng5K02Xf#a7X1|nLigxpOb>FBm7l`faJBqY1@iNNjl#Y3YwJ1o8~pzc'
        '8-IGEUp#Src{+9ujOOatiRJ0oc`%x<V<(oUV;8_^p^lwco{nvRQKOEXSe}ku1f#_|c4B!twh2bfI(A}tI(7++mg?Av<#B9dh&=;F'
        'XX@CA<>`J`z-VP0+brtKIx3>zFJz`s=>81=00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
