# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/igor/Work/misc/cyphal_ws/types/public_regulated_data_types/reg/udral/physics/kinematics/geodetic/StateVar.0.1.dsdl
#
# Generated at:  2025-12-16 13:33:59.676554 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.kinematics.geodetic.StateVar
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import reg.udral.physics.kinematics.cartesian
import reg.udral.physics.kinematics.geodetic

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class StateVar_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 pose:  None | reg.udral.physics.kinematics.geodetic.PoseVar_0_1 = None,
                 twist: None | reg.udral.physics.kinematics.cartesian.TwistVar_0_1 = None) -> None:
        """
        reg.udral.physics.kinematics.geodetic.StateVar.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param pose:  reg.udral.physics.kinematics.geodetic.PoseVar.0.1 pose
        :param twist: reg.udral.physics.kinematics.cartesian.TwistVar.0.1 twist
        """
        self._pose:  reg.udral.physics.kinematics.geodetic.PoseVar_0_1
        self._twist: reg.udral.physics.kinematics.cartesian.TwistVar_0_1

        if pose is None:
            self.pose = reg.udral.physics.kinematics.geodetic.PoseVar_0_1()
        elif isinstance(pose, reg.udral.physics.kinematics.geodetic.PoseVar_0_1):
            self.pose = pose
        else:
            raise ValueError(f'pose: expected reg.udral.physics.kinematics.geodetic.PoseVar_0_1 '
                             f'got {type(pose).__name__}')

        if twist is None:
            self.twist = reg.udral.physics.kinematics.cartesian.TwistVar_0_1()
        elif isinstance(twist, reg.udral.physics.kinematics.cartesian.TwistVar_0_1):
            self.twist = twist
        else:
            raise ValueError(f'twist: expected reg.udral.physics.kinematics.cartesian.TwistVar_0_1 '
                             f'got {type(twist).__name__}')

    @property
    def pose(self) -> reg.udral.physics.kinematics.geodetic.PoseVar_0_1:
        """
        reg.udral.physics.kinematics.geodetic.PoseVar.0.1 pose
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._pose

    @pose.setter
    def pose(self, x: reg.udral.physics.kinematics.geodetic.PoseVar_0_1) -> None:
        if isinstance(x, reg.udral.physics.kinematics.geodetic.PoseVar_0_1):
            self._pose = x
        else:
            raise ValueError(f'pose: expected reg.udral.physics.kinematics.geodetic.PoseVar_0_1 got {type(x).__name__}')

    @property
    def twist(self) -> reg.udral.physics.kinematics.cartesian.TwistVar_0_1:
        """
        reg.udral.physics.kinematics.cartesian.TwistVar.0.1 twist
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._twist

    @twist.setter
    def twist(self, x: reg.udral.physics.kinematics.cartesian.TwistVar_0_1) -> None:
        if isinstance(x, reg.udral.physics.kinematics.cartesian.TwistVar_0_1):
            self._twist = x
        else:
            raise ValueError(f'twist: expected reg.udral.physics.kinematics.cartesian.TwistVar_0_1 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.pose._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.twist._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 1184 <= (_ser_.current_bit_length - _base_offset_) <= 1184, \
            'Bad serialization of reg.udral.physics.kinematics.geodetic.StateVar.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> StateVar_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "pose"
        _des_.pad_to_alignment(8)
        _f0_ = reg.udral.physics.kinematics.geodetic.PoseVar_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "twist"
        _des_.pad_to_alignment(8)
        _f1_ = reg.udral.physics.kinematics.cartesian.TwistVar_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = StateVar_0_1(
            pose=_f0_,
            twist=_f1_)
        _des_.pad_to_alignment(8)
        assert 1184 <= (_des_.consumed_bit_length - _base_offset_) <= 1184, \
            'Bad deserialization of reg.udral.physics.kinematics.geodetic.StateVar.0.1'
        assert isinstance(self, StateVar_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'pose=%s' % self.pose,
            'twist=%s' % self.twist,
        ])
        return f'reg.udral.physics.kinematics.geodetic.StateVar.0.1({_o_0_})'

    _EXTENT_BYTES_ = 148

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8$6rBd0{`uu-*4MkcE@SSl4)77Wyel5&MzjD&Bz%?$|UWscecBe>HJtPI7zjW`Qe#qMxrIgq(&CCB;_B$ZlPIVyUs%G3K%XB'
        'pbwqL0R0E@RH%Ju)4uef1)8_^p)Jxr6)jK%D2nO5<o8hWwViRYnVAfh0^)Nil9%MAK3^W5bI7!Ze|7CglK<(PXl_=WYCT_ablcSG'
        '<_&GRuIEb?Yqe=PrmK6M16N(URdHLk{?=ww_dfCFKK6d%<vNK{LtAC@^R~W{Z&huro^KkPj#+W?ADIn(RdacBMYpOtYvr%HnybH~'
        '*<MF3t?9O7S`E*TIwS9({fVba>d+s0AA6m#lIFU$x!iJf$GgThwZ~3|OL?8d>!x0>_IEB-s%oxQa`_$`vEWN1(K)xjeJxs!zpKWG'
        'F-m)7q}iSr8FY1UpwqMa?{uF%KEK}{&4&B1F83O^rfsg8uDQkrZuIrKrMcVB>{w~pbW3%;vEmw@dWj8YMRVNJD%-4Q%y$kIX?4C@'
        '{uMUwGM~lI;Lp4_z0P#WakWNOv#Wz0ZLxk<wUvhHwyJ!?*KMuhvNP|nU&QNZvp#<DvGi4a9(?A1{IPt~Yb~=gA=lZM2Rl4ms#+Dc'
        'uOHZ2)zli-_yYZtmq+Ub^^$SH_@?o#En~s>&eL@;qjjsX5*&^3(q0GB{}n1NZLOj;@{XBrv9p#B&SU;vv#MXMXm#RaNR{ZP_ca@j'
        '#H#M<HXjR#eW7&@4(Lv4c{9+rpLoW*#t$6^MOAOwdWET2)w|glFI_h`^lGVT*>1_KdRID=CC6&n6`jqf>!qf~e)64hZtCW8zEro^'
        'kg;DqQvq|M$Y*}ybv`P*&A@aD=89z(-nHzH3ah45DO5I_hE^}FI|Z&^PNCUauA7w-6NOftZ@#Z>P9Zo)1;;G#b5sb<QK5g1@-O7i'
        '=eY)WKAHzhhUT!Hv-O6{MPbdX=-y4^C1a_R@sBr9{sx;JNN+OOfY*sRCS!na#Oox1bSE|NW6(Q?{i80qR>`(3*YD10YHR~WxwH7B'
        '4mCKA;nH%Q3C9`Ix4zD>qjJS*uao{=(|yCAzRD({be(v~YI+@IuTGrJ)n$wA4jZ=1`l`j$lWWxPHFaBaExWIm$x_8I+11Bb?@Sc6'
        'YSnD4>{!V7F`s*-RcAxBDb8g*tZDU@?)}ossh7IWGP_1LgN{5^ZY{IJT{RnAidjS3;EfS3$83yv-|7%wPwJ{M*f_UCU3D1K32ukG'
        'Y7%w?^JUB*#dHeu$G9Ess%cCg;5OY=$GMfe>IA;eVEsvM4|LTjZc|<LAh#o3bsEdfp#MYMPIuMA+)j1XEVr4i`V6<@U3C`QIf8zU'
        'VtdE9O?K7e=<fu#v979M`zN_Q(N#}zd%UYY%k8nQdYap#UG*E>9_gxQxSj2)&vE-qSIu#o?W%L!9`34VxjocXpXYX_tIlJ8&vARO'
        'tLCxa1#Tz1>Ur${3*1h0)eAU|ix`jJ!twkzw_{!Pn>em-VSE>GeBZ`+y@=!d4!4P}`a3w@?{XXOs^7zLzl8C;gyUZfemCk8tO2_L'
        'y9Ij-_BQMt*t@XzVDG~|2<&Bf2#qW?a@1I$#v(PAs9{iJgBn}ZxJ8ZI)VM>9yVSTxjr-JifJTdX68c6{Yxs^MzFT&dgDbXHcf)I('
        '`>M%Zk&3P?>+ZU)Hx$><6<>>$Rb6W+j;<+neNC?`xyx7Im{XYB;xBUDU!=($EXBI+f2B2Cz0uI}3YT#1{V230MO(JmBwvVil4sWv'
        '-FS~P|2^ZZ@qOcE<3Efaw2TjK8oz(VxW=?_?bp{r_GQ6$5DRb+3w;N%Kn`NTcMzHWztFz|7*(eBoxk`#7EydJpAF-S3VAy7O6Vrc'
        '`{O}}nNPjNj?l8Jx~-UwQZblA%Ldd^*k&t6Fh(0}hQ9=pE*iKiuf3`;XKxi9IOYxA@3*dPS}hDOTg{={4Bol^qZS)~);I6q70qT>'
        'Wag^yy=CLfy-v^2`Q<6j27-D2{!n<G5ex>qF!hInxok8bY{|f9){Qzl53fCu^AHSc({Ow#H`a{JQ1SmDY;6u)1!i8c8r+R&?0Pxr'
        'j0RT|c7^5_;D`5C8y=D*f1)<RT6-=3(_q(rMwb`k=jsrHWsCV{H`%{mMAwk$8uFWV4KeQ1g<}UEy2IIMGd9`}VIwB65eFMFun`m3'
        'h=C0mY>a>n8ElM!jTqRF1vW;(Mht9>gAEyM#K6WB*f;<-WUvtj8(FY14K^}hBMmlWurVyKaSUwCf{nvqV;XEsf{k&oF$Okdu#o^8'
        'F|ctKY~;Yk8L)90Y@7lc3fMRfHjaXgS+J1>8;8KgG}xE|8yT=M4mQ$YBLy~Ou#p5C!(byOu(1F(a$qA1He|5T1{-a#(FPlBu+at^'
        'ZLrY>8*O5vO>DG@jW)5-CN|o{Mw{4Z6B}(}qfKnIiH$a~(Iz(9#73LgXcHT4Vx!I3_&LA-h-ipth-hFO+z2iWJqAPXAuvb+3^BkU'
        '0fx8$LmV)~07C*WNPr;)7*c>CEx?cf3~9g+0}N@v5C;qyz#sz#2{23oh7@3k1BNVMm;wxGz>pMRI06_B0ftGykOmARfFTALP6Gx7'
        'FdPL8S->z27&3q%4H#s=Fbo(Zz;F&QoCOTe0fy6n;Ur)<4j7IAhAd#10Sr@sVFECu0mCR@NCJkq0K<8}kO2%!fMF3ZEC7ZaV8{Xn'
        '88Gw!Lk}?Y07H*p=n)J(f}uw+^azF?!O$ZZdIUp{VCWGHJ%XV}F!Tt99>LHf7<vRlk6`ExUK%1AA{u_<X`tv6#Zx>UQ{N-8azaR~'
        'XpNP+p8sJ>b9KAnue)bnrE_GDRH$uhn_g%7b)J+60^Kk3ueK-l4wUq|zRE-YL1MI@q)`TwG?UvBCxb~79-PpcTE%oXJ#~2ZpvQV='
        '>P@|=yXNk}@>uC3zUua%gwplLFLE;@H#2fGNlS*;H#ToTM>HN#uGw)(s{L<FlAM8Pa_xyH5q&)>^z~?a4$+Sw8%sg_b=UM@!tcQA'
        'qy{7{h`2u4Ea2w^U27>eT+t0|q%4uL2+A^M*(UP>v;jvY$XM0>i;0VIs`f8jX#ShE2h&!qFE4H7=(}aD{^Wh#wiMe6cATe)cy`F)'
        'g=NaRq1!rgP`X2@r)8_U8RVW6&E^R^bETnIm37lKb}SoY1;b?3i>aj`|K}(T%XW=<<vp6#HOHM--lxf`wcdE#eAKXC753GoqxP9V'
        '`oHLAFS^-_ZuaPAul7@>kA5id@}(i;CjYa4$3hYui-bT#0z^n4Vn}c-WDt=C5eb2aaS$;MA~GOC0uc!ikp>Ynf@3iaB4iM87(}E&'
        '#1M#>1`#QNh{GUa97H5QgaRV6AR+@IWDp^Nh?5{<7DOBb5or*S01@*b;*8)}%z}t%5HSuSWDpSp5f?zjIS`Qp5zm5%;~?T05HSrR'
        'CO||AL?i?v6cDihB4iLz1QF*!L<U6M0ufsvVgp1NAYutbED{k5L`05=$Py7Uh+w}+AmO)+u(c7kw!+q}uys3Z-3eQF!`8j9bw6x9'
        'pjJSK-wGpx5gZX55gY;>aKRHn!KWA{tbG=PKbEV-`0Z;yM3)%|(Ov%M&nP5U8)1v7GrM|xwFB|6w@k3u_PARHaktAwPHJ)J5gfZA'
        '!LgI}aO{#GH7PiDbbl;?)Z`weK;+mR0I3;}DuL7_NF5g(yD{PZI1N%IkU9xclOS~#q-H>BQYZzQ5gfZXNL4^;7NllCsti&kkoqi0'
        'Jql81K<YS19T6P6vmo^}NIfpxA5VeQG)PT?R0*VB1gUwDItNlugVYlsbrz(~fYglO*ewe8$7P`uNCBx5NWBG8w?OI!NHsv}5|O${'
        'q%IJtIU+Snj-5=P7DG^rA*jU=)M5x~F$A?3f?5ngEry^LLr{w$sKpS};sB`Q6>CkiO<qJ=YS}I$cIofgozmOQrf#3J%@xB{Tt0iH'
        'uG5`le+^z5X`34_rc%nz&j&#nesH^aE&SH6{!?=N)^!f^gtc8;YdH1bCRpRennB$q|AaTk+A^=L<lpbI=_T0rVBg>Cdtu$@&pq15'
        'zl9F+A$;{8r{3E>-S2tz!wbr8pVhOrR!zMxbhFeyPIS9%TKU`$>-575tlMp?g>}2NV+p3bv$a2Brgl8BJqoh%Wkx~X(d=CUAryRl'
        ')L_F1J=gZM#~W(@6GU!@A}=!XA|o$y7ca7wOHc%&8)JB|Kl{gH=yULp1=meXZ6pOe#soZ4z(WQeDZzD12&s*<fJYK|B!P!4;6X9D'
        'S>TZnTsKN>q=3gP@Q{Tn?iBD)1lLUx@E8+P8?(S84Lr^XcpL;CN#HRLJQUzD4LoGvaZ$kIm=Kd20Uis$BM&@I1CLq3b(4kEh5|em'
        'fJYN}oEPvgfX4#xkcF7sr#n&`<sDVr3b}3)(XkNHkqha_hIGh8hx&lxa`!1NcaP$7cPTD+hvIU#DK2-5u;|7HBM%W25fl*=0TfhD'
        '(DYwGuy<Kf;h}FGsL(@L`M1_h$KC(y5#}GI+kN&aR#2_!b&D4z<=@dOu4P|*NCnkHA}sqXf(jxo@%=?y;(Jv(m5rP1-{Z$yM14vM'
        '`XmeSmV}^BV!UMx`jmt|4GH>`hCa#Ar(q%9G6Q{@f<8?M`ZOxUTjGLGdmQ?7RM4j^^yv`vX&U-8CFs*Q^eGK}N<p7w=u;B<Gz@);'
        '3GtQ!^eGR0ItP84hdw<IeL4$$niKTtIq1_F=+ifZc+0cUr&G|Ulh7vx`jmw}$<U{=5N|0%pUTjuGW4koeJVqr%Fw4W^r=kxRNkRa'
        'WzwfI=~I~!X=O^Jl_`-{rbJqqw5d$mR3>dIlQxw}o64k3WzwcHCDO`$Y0CI7VkkA)KS!@vjq0|lrz<1uHvFHGUv$+IX-EMY@~Bl$'
        'GIikbm)Zm}^i@<n{d;nt>M2s0NM$0G2~;LoXKsh)zwhPL8-7zEWEHa^)C=YJdMnOzJBzm&u68MMK_YR8#Nlfz4wJ#lu=esnzAZB!'
        '<Znl|`ylogQF*;hOdi)4$%q|&#XiYDj6^<3Bs-Dp?2w%ifXbbcS6>d=eXk@);`;9+;?H&MRoa}>H(c9nIA&$8|MH<)kKZ=^BfA->'
        '{TUapzZ}_~$6Wt{^O#{^r{D*6cB|+9?q$nQzOp0I6x&=etHDt*XYAsuivQ|3rK(>ydCB%J4%#CmK}W;AVT%TVrl&p!`eCG*k!D7k'
        'IiQ)fAIM00Mvoyxk0C^lAw&=5L^MP+2ybAB3ag{S>Zq{#>seU+H&3Rp`XL3<`>T)swTh%4t5iC*)W7QwKfJJcmu~};TP-+qJFBL1'
        'e#P`$!SU;xck6RW(Zo1|zolKieRvUdj%~=_2ezSIR_;e4{&iH6YJbNg5pSp1pMM+O9*MZ|<whc&Kuz^vI6)4}VV?Sk!k^3is_MvR'
        'jC{t(XRQ6_D3wuXc*STY_6S78KZl5<@P-&kAVL<1hzmpv2{E<_;SDiFgajfE2}Hz&rwk?pBIsq<Qy^kUaMUCaF$E&xLX0g1B2Iyb'
        '8Q~2vrv)O?AVLBWCqcv^5HThYaYlGU%#`qy!9^j)c2Xc>LU<YW0*E*dB61)?0TEfjQKJ}}Bs^ts9z<+_h(&>jPlY$cl!cdJD@24u'
        'L_8oO?h_IBh={vH#2q5yHW6`)h}a?`Hi!s=h*%;b7Kw-jA|gjbWXU_rY%8ITfQW#Ifau2++@L;r@NG$d#Y^obYkxe(yxPA`Zue?8'
        'zpUp3=|9%nEyMQORb5y71(fTSt*{j|v+m@TxA=d!!8fAl8?N4{I*REAZ$%Psu`0UrxbHTS!~gQ{srQWkG||ts4L&<!+`qz{gq0LI'
        '37-zLS?mwZ3fB>5@E=Y7{{e&4_Y-Jw000'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
