# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/igor/Work/misc/cyphal_ws/types/public_regulated_data_types/reg/udral/physics/kinematics/geodetic/PointStateVar.0.1.dsdl
#
# Generated at:  2025-12-16 13:33:59.668458 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.kinematics.geodetic.PointStateVar
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import reg.udral.physics.kinematics.geodetic
import reg.udral.physics.kinematics.translation

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class PointStateVar_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 position: None | reg.udral.physics.kinematics.geodetic.PointVar_0_1 = None,
                 velocity: None | reg.udral.physics.kinematics.translation.Velocity3Var_0_2 = None) -> None:
        """
        reg.udral.physics.kinematics.geodetic.PointStateVar.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param position: reg.udral.physics.kinematics.geodetic.PointVar.0.1 position
        :param velocity: reg.udral.physics.kinematics.translation.Velocity3Var.0.2 velocity
        """
        self._position: reg.udral.physics.kinematics.geodetic.PointVar_0_1
        self._velocity: reg.udral.physics.kinematics.translation.Velocity3Var_0_2

        if position is None:
            self.position = reg.udral.physics.kinematics.geodetic.PointVar_0_1()
        elif isinstance(position, reg.udral.physics.kinematics.geodetic.PointVar_0_1):
            self.position = position
        else:
            raise ValueError(f'position: expected reg.udral.physics.kinematics.geodetic.PointVar_0_1 '
                             f'got {type(position).__name__}')

        if velocity is None:
            self.velocity = reg.udral.physics.kinematics.translation.Velocity3Var_0_2()
        elif isinstance(velocity, reg.udral.physics.kinematics.translation.Velocity3Var_0_2):
            self.velocity = velocity
        else:
            raise ValueError(f'velocity: expected reg.udral.physics.kinematics.translation.Velocity3Var_0_2 '
                             f'got {type(velocity).__name__}')

    @property
    def position(self) -> reg.udral.physics.kinematics.geodetic.PointVar_0_1:
        """
        reg.udral.physics.kinematics.geodetic.PointVar.0.1 position
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._position

    @position.setter
    def position(self, x: reg.udral.physics.kinematics.geodetic.PointVar_0_1) -> None:
        if isinstance(x, reg.udral.physics.kinematics.geodetic.PointVar_0_1):
            self._position = x
        else:
            raise ValueError(f'position: expected reg.udral.physics.kinematics.geodetic.PointVar_0_1 got {type(x).__name__}')

    @property
    def velocity(self) -> reg.udral.physics.kinematics.translation.Velocity3Var_0_2:
        """
        reg.udral.physics.kinematics.translation.Velocity3Var.0.2 velocity
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._velocity

    @velocity.setter
    def velocity(self, x: reg.udral.physics.kinematics.translation.Velocity3Var_0_2) -> None:
        if isinstance(x, reg.udral.physics.kinematics.translation.Velocity3Var_0_2):
            self._velocity = x
        else:
            raise ValueError(f'velocity: expected reg.udral.physics.kinematics.translation.Velocity3Var_0_2 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.position._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.velocity._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 480 <= (_ser_.current_bit_length - _base_offset_) <= 480, \
            'Bad serialization of reg.udral.physics.kinematics.geodetic.PointStateVar.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> PointStateVar_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "position"
        _des_.pad_to_alignment(8)
        _f0_ = reg.udral.physics.kinematics.geodetic.PointVar_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "velocity"
        _des_.pad_to_alignment(8)
        _f1_ = reg.udral.physics.kinematics.translation.Velocity3Var_0_2._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = PointStateVar_0_1(
            position=_f0_,
            velocity=_f1_)
        _des_.pad_to_alignment(8)
        assert 480 <= (_des_.consumed_bit_length - _base_offset_) <= 480, \
            'Bad deserialization of reg.udral.physics.kinematics.geodetic.PointStateVar.0.1'
        assert isinstance(self, PointStateVar_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'position=%s' % self.position,
            'velocity=%s' % self.velocity,
        ])
        return f'reg.udral.physics.kinematics.geodetic.PointStateVar.0.1({_o_0_})'

    _EXTENT_BYTES_ = 60

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8$6rBd0{`vY?Qh%09S3k(vSitoZP{@gHO>Q*x~cOdrAgbQ-9yv0%~G&Qy}C^ebSX(m7atW$R7lFT3v^=!Y)A)gBTx<qu)W-i'
        'zS!%bFSU356Z$gPt7024V8F0oSkc{)-;-p<cAGA1JCsI}JBiehchu*2{M|Y3@UQ=RAr=032iqHUyKa;fn^?ML=x=LPgOrt;*=(D('
        '?vTKnSaz&V&FNU=)r~d@-V2W24BiPAy{yvGnr!<Si>#JAbxSkKZMtFWHM@LWZ;__v@a!rv>xAXXOQzm(mL1I@S2Qc|^2!>qY~5@H'
        'H06z4LH@l!PRT<*3vLG9xS~0ZrB^!+v4gAZc-x$5Z?C}1UeJkA@1NnAQr8?!arkM|bo3_8dgc2#VScW3gpP{Sq6Ky;w1~2H4U~HP'
        'K1$uG$nEOcw)Cd%=xeN=qZbTQb2eX%aiyv|ia}bd4h`h<tnM|<c9bSNY(N*hxh3&&{;~3NY}+Nii8uI9gI5A?R<RweRoATgU_rN7'
        'IZbV~r8}KEKkzk6t2yjK+3W&dK%SNH^P8!!>gVpK;ZN9>uLPYcyApYWwRv>H!%E$(v2%UH((1a_y2^LxU%Vs89hJ}1W3)^wx9BN)'
        '=Id3NQNwJlMzx`5x2s71TPSt3wVKu{+j_afu39;|j^)?&I$5r1hWIuQ$tm&G`#)=sY?C;|;%$*)Z)o1Gfo?*nZbW_3I{|%}zGyQP'
        'b<(y-jdeQp;9YN0xu&m^y3#f+N73uSWp7%s&5l(gY=c3Rw#L5l-Xu>9y;@cblQkLp)-SQ1aD9nyd@t~>S6*W<?TWr?T9wyL>w2ZB'
        '+qFt<qfIqKdCRWw?#8aPJ5@ukDXdfI82s@4uE?%L*QjFa6@HB>(KV{{uTlB2@~JZK1A>s|E`@3~J2{KA9NsCc=`|9(OV83JuNc-h'
        '>aAOBbJSDjq5}k8+SZu?evrV+fwVU^@MR$0p0L)6V=9(uI$?2kTVn^HE8fKiRn@2-!%Ed)9mf&TzxDeWRx2m|I`9hL)18;X*URiB'
        'dO9zonC-xmwkyQmXjV;jI;`0)k*3LdPu@qp+$NUhm{z~P%qcahvzrAqy{RRwUe{Zz_v}O+zV&j)U`@3V-^xl@(~J%Yeibar=Y6}%'
        'ZfWhPpg_)ds;s(Ay~Vp?meJOEW`uXgtc`ft@(}-A%9qnfGdvyg<zc+e@^sjjb4W+9J&*09cs+*g<2)Vp<pN$$@U-B|lRVA)@)X`L'
        ';`7ryo$%!uo{stQE}o9~@+|h-jq>MsI_t}Ocsk?DC7u?2`5~T8`tn{JXCCG3!}0d>H0R3)P~JhFrhQq$@elFzpf4Zh=>cDUn5X-F'
        'd4Z?<eEAWc&inEap6>PKM|t{?FE8@6<jY5Sy2qD~@pR6YkMnf5FQ35qp5*B+UoPXkD?FX{<x@ES$9OvB%coI~GiZ;;QJ*JxI_}F)'
        'qF!gwzUNTCr_f$cqn_X5Y1Ws&jrx9vrx{=VF6#XZ+Vec>e=+*r$SX)G(siV_klsf6KGF}6eu(rVq#q-_8>N@>L&%gwW>I9$iOfZj'
        'SrHj3GV3C9OJr_~%=;qqfyjI)G9QV|$0BnVnGPFCkoC6K3debPuWDDLJGN#xy?dPVyv~OrH6m4s^A;g3$)Q9F`(mj{w3cKOO)|(D'
        'F{H&y%P$?3*svws<yyE)n-8!g^IG_p)^bRzrIjV#h4aymB#tC$Rg=BsJF!B_>|R3X54ia!>0$Z|eTx2xKHH(o@6uN<)7MyExc1-o'
        'h3w5rI6$mmfLQ4d5G!JUSP2J+tp9(ke+QsHWWBxj$M0hoDIA%zW_(%_Bb^gcZ<uf*Y!6Y*^4P1ahNe{~mZaNKjhZ%ZP*Y-ut<k8B'
        '*4c(|57u>whP(X2^Aa2EHBo@AzfHn&4Q<2hpn2KHZ1HHo3nw=^to>QpynyF4i`|jgP=%i@YiB;{4CqyUd&;neV1xCrDFSZ<jlphA'
        '{pMgpHqjt#&uGj{Xq{b$7aquUh?<qs>tR<;Tl7Y+$6xE^ZVcQ7c0Xsf_%Nci<?X~9jqWDw4$W`CpHbSsql13B-JWkp+usp47W!j('
        'h%s^5sO%>D`;+AEk=#ALX?G8LN8B>*;X!O}!(}$y9c-jyHZri0hK+R0MjAHqurUG~dDs|-jWlfJV>U)%BMlpqu#tz2G;GYk#sqBS'
        'VIu<@CD@pSjUsFmU?UG3!!aBCVPh|B?17D0*qDZmN!S>NjXZ2*VIvJ2$6#X-Hjco?0&E<H4GA_5z{Wn<*b5sa*qDQjS=g9?jUsGJ'
        '!bSl$#$Y248#&k*hK+R0#yQwngpCqx<YB{w4Hq_C*l=OPg$)-rT-b1h4OiH3g$-BOaD@$5*l>jnSJ-fc4OiH3g$-BOaD@$5*l>jn'
        'SJ-fc4VT;aF@N$%G$a}l4a|WR-5R<KLw5%ZsThVdFr<JX6T^@JhBPo_fguG9W56&5422kmEHD&+Aq@-#V8{SN5g78okOGEjU>F02'
        '3^0^{VFnlqz>te!m<NVAV3-Dm0x*mKLmC(sfI$L=eZWuxhFM@J0z&~9^1v_*3@KnZ2@J=8;Za~%0ER=rZ~z$QfuRHpyMbW_7^Z-s'
        '01TtRkOPKH48tj4C<4O@FkA$NbHK0&3?*R5149=Wy1>u{hOWTS6&Sh#Lswwv3JhI=p(`+S1%|G`&=nZE0z+3|=n4#7fuSofbOna4'
        'z|bAMH6$7m4c~YTh&yGY2rdt$56-7}^V>`{T9&pEc(WJyEJ75SewM$rc_wZ`AqHvkSba3{*q>D?4$P`ty7Q@+)!@+st*zB`XCshv'
        'TSp~KZ{`)!CXT*!G&`+a=O5i1J1F{LHC<U{<kkBiKNKUMjgilRd=BLEG4ffEFMxb5Mt&URb09wi@<os@fP5b0hhyY-gZvE0Pl0>^'
        '<VQh12lAO1`2!%o59IfPd<o>|Kz<hFXF$FP@{=H60QoVH&x3pp<cC2%9V1@>`7+3#1o;yne;nkGf&5XBUj+F_LH-EHKLYX#ApbDP'
        '9|rkDATNP@3FPx2uY$Y^@+!!yAg_YF3i2w*t01p}yei16g1jootAe~L$g6_9D#)vXyei16g1jootAe~L$g6_9D#)vXyei16ee#nv'
        'b4_EYTQ#C|EQi@&nHox^-Uz1^-#mSF?6o%2b<)yTsUtaj$5n%fsA&JQJbr5F>rr%6#A64y>$X%U*Yp;tOBUf_S{`gRB~5ZziL7(b'
        'd8pdZT08`8nVr=r7HhXjO~0m-dM~nD=>>MnV=qMgN-tQuUHn(Xex(<kFBtUgg~J<vPN!0IZ=;$?r5b->`N5d@#+MoszoJ=NgvII7'
        '7Yi!qd&@h%!npEhMS}m)3;iaewq(@yjUTl&{>3_=@R|OSG(>Ome?Gs6OiV<4G9(oXaiwD-(y_^qOiV-(B2o~MiG{ePAR-MBg_wv5'
        'h)6@kOl&e_9wKHSVl*bA1QA7u$U{U5BKAYX97IgTLR>=-u>cVVAff~jGZ0aLh+Is>afmnq5r-gRA4Kedh#82Oh)srMAmSWEJPr}3'
        'AmRi>EJDOWY*3Seh!R9BLBuJDC_=<7h**aR3K1(1aS<ZULBygEQ4%8Z5W&8GAQ9#+_Hrw|9PQ=Sd%0V^-0fcO{a)^aUhczQ?xSAr'
        '<6iEr$VEQFT<;-2;gRr2c-+H7tTqwj^?M%t2NqI3vEy=H$I@E15v~O&Um=FcpWV+4tQAi0yjJ*NY?bC3ieP2c*mM1v9TsUe{>JWs'
        '(Tm34`PjT4UXTVCZBB1mNIAHOvhh#$F*&p4D7EoPzw}fl+--AAK}uo@NlYP$DQu1@6vN<w(q?~cQZrk1bSxTwgl^1d*`xFChf^tg'
        ';L*A9z*iBAKBR&^Wb-28P0z|(t`E+O0s{W)7*RJAJsLmQWx${Dblms@YpLF3MbgV8y-d=}>^NDm!+>C$`G#l!ko$ZCfMil3p_$OU'
        '?@0yk**6x$Q9&gd5gdK<^i}EprWX1!_+Ri5#P8UBvGEDd{W7~b4DbGr!|($SJC(tQ9X7r=9bcq=<0bYv&631mLV8Pg=s@MlV=q_v'
        'uQ2gx56y`dk+VNqZzZ{ANOq^n&x*IqcF#!zzbAD+i^|6bsuFmGO;2uL-)Vrx@oYFG8cO=zq~A^YUEc3DZf7wQkj#uFGh@ljShBh='
        '(U53}t?uhbw4!HbjHZ9X15DG6vm<OM{oCQqL+KxVsViE<|Aw;FZ+p%!6C(BZlCGJS#6GI&hW$l<k8)!3f5GxK9`HJuehhGME|cE5'
        '%<lcgoLB{Lhi|&m-_-j|d;|YRl>Y<UA&idqMgRZ'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
