# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-12-19 12:32:02.289938 UTC
# Namespace:     reg.udral.physics.dynamics.translation

from reg.udral.physics.dynamics.translation.Linear_0_1 import Linear_0_1 as Linear_0_1
from reg.udral.physics.dynamics.translation.LinearTs_0_1 import LinearTs_0_1 as LinearTs_0_1

# Convenience aliases of the newest minor versions known at the time of code generation.
Linear_0 = Linear_0_1
LinearTs_0 = LinearTs_0_1
