# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2025-12-19 12:32:01.060333 UTC
# Namespace:     uavcan.si.sample.frequency

from uavcan.si.sample.frequency.Scalar_1_0 import Scalar_1_0 as Scalar_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
