# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/control/external/public_regulated_data_types/reg/udral/physics/kinematics/cartesian/TwistVarTs.0.1.dsdl
#
# Generated at:  2024-06-20 11:16:16.738885 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     reg.udral.physics.kinematics.cartesian.TwistVarTs
# Version:       0.1
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import reg.udral.physics.kinematics.cartesian
import uavcan.time

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class TwistVarTs_0_1:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 timestamp: None | uavcan.time.SynchronizedTimestamp_1_0 = None,
                 value:     None | reg.udral.physics.kinematics.cartesian.TwistVar_0_1 = None) -> None:
        """
        reg.udral.physics.kinematics.cartesian.TwistVarTs.0.1
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param timestamp: uavcan.time.SynchronizedTimestamp.1.0 timestamp
        :param value:     reg.udral.physics.kinematics.cartesian.TwistVar.0.1 value
        """
        self._timestamp: uavcan.time.SynchronizedTimestamp_1_0
        self._value:     reg.udral.physics.kinematics.cartesian.TwistVar_0_1

        if timestamp is None:
            self.timestamp = uavcan.time.SynchronizedTimestamp_1_0()
        elif isinstance(timestamp, uavcan.time.SynchronizedTimestamp_1_0):
            self.timestamp = timestamp
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 '
                             f'got {type(timestamp).__name__}')

        if value is None:
            self.value = reg.udral.physics.kinematics.cartesian.TwistVar_0_1()
        elif isinstance(value, reg.udral.physics.kinematics.cartesian.TwistVar_0_1):
            self.value = value
        else:
            raise ValueError(f'value: expected reg.udral.physics.kinematics.cartesian.TwistVar_0_1 '
                             f'got {type(value).__name__}')

    @property
    def timestamp(self) -> uavcan.time.SynchronizedTimestamp_1_0:
        """
        uavcan.time.SynchronizedTimestamp.1.0 timestamp
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, x: uavcan.time.SynchronizedTimestamp_1_0) -> None:
        if isinstance(x, uavcan.time.SynchronizedTimestamp_1_0):
            self._timestamp = x
        else:
            raise ValueError(f'timestamp: expected uavcan.time.SynchronizedTimestamp_1_0 got {type(x).__name__}')

    @property
    def value(self) -> reg.udral.physics.kinematics.cartesian.TwistVar_0_1:
        """
        reg.udral.physics.kinematics.cartesian.TwistVar.0.1 value
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._value

    @value.setter
    def value(self, x: reg.udral.physics.kinematics.cartesian.TwistVar_0_1) -> None:
        if isinstance(x, reg.udral.physics.kinematics.cartesian.TwistVar_0_1):
            self._value = x
        else:
            raise ValueError(f'value: expected reg.udral.physics.kinematics.cartesian.TwistVar_0_1 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.timestamp._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.value._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 584 <= (_ser_.current_bit_length - _base_offset_) <= 584, \
            'Bad serialization of reg.udral.physics.kinematics.cartesian.TwistVarTs.0.1'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> TwistVarTs_0_1:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "timestamp"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.time.SynchronizedTimestamp_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "value"
        _des_.pad_to_alignment(8)
        _f1_ = reg.udral.physics.kinematics.cartesian.TwistVar_0_1._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = TwistVarTs_0_1(
            timestamp=_f0_,
            value=_f1_)
        _des_.pad_to_alignment(8)
        assert 584 <= (_des_.consumed_bit_length - _base_offset_) <= 584, \
            'Bad deserialization of reg.udral.physics.kinematics.cartesian.TwistVarTs.0.1'
        assert isinstance(self, TwistVarTs_0_1)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'timestamp=%s' % self.timestamp,
            'value=%s' % self.value,
        ])
        return f'reg.udral.physics.kinematics.cartesian.TwistVarTs.0.1({_o_0_})'

    _EXTENT_BYTES_ = 73

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8fDd$L0{`usOKcm*8OK+oL{Sti>tQ*J?bvI_u_?!*U$LX6O>4)7qjV$1@FP{y*5r~LYgS(Fvip#!paIfDTf11G1hNHu?9s;p'
        'efd=IQou!nG)EtUp4_59QM5pf0)_j{@;?-{7Gt}IUP=Py_h}z9-_FeMKi|yK9}WJb@TwAhf<5)Ms#`S+MVC2-ZW<rxWs?<(6}wiq'
        'UBhExu;r5H_!ZB0*yXi43qKBLz88KN=7XW4rPt{EF^4S|{Hmjyg*snzjfz{iZdk0Qd%~^gj>lX>w+feU7_RrO?p$`mAYEK#j%(Of'
        '$dzFDUHBh|nxYN-ApBk!j23mzbBwZ2H;3P*+Iqy<xhf2X&Ku0EuE&=tR&`G=dLn3^XdmQ5!Cqfqtx!0gQDcQmYgUCjwq<<4s+Z}2'
        '>*=+6$cOoeHlQgY5}u{n`8aN$>J>-bF=~cqtWq3PS1i|9wpjHo%VW#T+1P5M#j@cQO=c~7Jk;hW%8KrK#hP8ED0c<hFUW$#ZH2RR'
        'Zb6))rWyEtcrgsN6)8rmsyo&0f^PX`dbH7+QE_aSRcxyo27|?_T?v=|oKTd@oT-*yD>Fy6uc=*ExvIx?Pv!b5Q|r3xva0GDR)wjq'
        'U1O^5P!*2utf@8n)ACfqqU)n8y+TG5isMwM?HJ2+I&TzM;c#@7XkfLhyKF`^T(!!s(V(cRb>__K^}1<PXnfdKK^4VRe8&;xbZ!wf'
        '`7X;)N2z6|I_x_>^$p#A&9Q6irMsQ(iwaX~6c}?3t1e^FMHQRMb?fw?hP6ybomGRLEegemYR}M9P;jfd=`#_fXR8)l70pCn*G&6H'
        'JHF2Olc#2>Nz@xgmEvR-onm|~lTp=K_4w73r#7}MU9OjH-&2ntpF63pG2L+wt2ek&;o?-Cdd^!bsAtquuS8{b-Ai%%G<F>IhV7eG'
        's)%Y(Ro}8$g}JWo80K0#1R4mc;klh?soCf@idOW<NvhT3w(p9oqUz~%)u$p<oob_kS%ZkAFlZdB6~}N5x6po=vnGuNqcVH;%%YmN'
        'Y)?IZZbqe%U{PB-R3AZ2gTk+i_Igz<uMwo8#=5>{+IrN-)KMf3g(&dLva8gZ2!EL_cDZhvqKCzBTQ=Ejba}gqYizxtYK#uF$Eero'
        '2O1OyJuxgq8#v;uMIED3Bf5o<Ko|?sXKhPh;&r&=Q+zkPz1ke#$M<WB;E5k>qcePEQCocH8;c>I2@br^96MfhG~TG+L~C5P>>E}g'
        '3{u4?pfGqriUMoYX}}3F+aL+)i_!ShO&JeA8H~^)SHw{vhv(sUB=BPBmi;mdrn+>nSYB&Ou6T+(-@#AtS)T-@%BWJpiB-c}!C3K{'
        '(O}i0=%}Jm4HtunqHFt3h0zI<73(_5MKCOkX_UiY<O0cj<AON)G0D@w5fTn=3tdmt4Z4uVqvzNr#mE{ow!||8JL`U#04|d7`=+RO'
        'U1{lIQf+~yazvYj!R}2(ws5R)v>+NS^n|QU6}j$Ga6$%(05!Zto$>p{Hu$0jRn#Cx4e5aGkSd7A7UP%T)(KqihV5LRjmU7j>Wum>'
        's+2~I$2X8h1=yzF)`Cb1*6X1^xUtNMHELbEMnYFb#bVr+Z7PXWN~&?h;woKZJF{+`Rg7y!*LbIi;yNn`O)i_%L<i(}S(k8nXfOVE'
        '7-ZitytkvjFR{*G4w6N?9tLW!Lfo}l*{1%XR$X8<8{+s5QK@^jvpyB2iWN>W5b|#YTQBHUp^=YW#C36Y(Kk(+2I6P=$sdP#ZLaB-'
        'X+p2JO9-{JU#91*8J3vd$k7|Z85UC<jTTX;HX!a(npy%jDQu#t4dU-1VF#L83de_WJPkX7;~8O7O>Gp{XN65SwJpL9HnlNazg5`L'
        'rZ$fA6T%KPwMmpSCG2EV+a~OIQ=1lctf_4mHrv#m6E@S-a=8C_)Vl-q>_j=cP~Qu}?rdtih27EA_6YlYQ&WY_HMPCMKG)Rt3A??i'
        'y(sK-Q`;}>wx;%yuv1O#0OC3*>_k(`Bfc47w>Gsyi1TG(w=}iGh<6sxTR_}LgdJ&WM-l%qVTYUAaXiNfw8txWo~U1wP3;t(>s7Sx'
        '9G>q>?S9u@gZ(n>S72X<{VMF&U{Ax&!!E&c*aqxP*xRsoVDG}-gS`*?0QO<qE~E$G<fN0A&YX1SrL!a*E}e#SZc692bnZy!u5|86'
        '=e~3vNarCOpRzof8E8Hc5|3kLA@DTwjCkvL=S-l839OTCcBQRHo-xaAC$UJUV@YgRv4@|f*rzOW4>D}mDEO3T6;_#PR}4ya-enb1'
        'j}wpO*InuL&K_yL<LGOY{GJzcTU!v%h(jB5>n%lQGLeuX>E9KMoTr4u+i(@l|0>P@$N9mV)GalAnL_kM^8NacCY0{aqeqW06_cQi'
        'P?}!X#Z!b@l3(FVZ2|lyzuKjflNVW?dB)~yn<!ovx9WVkOFPwOGzv_u#B21=>M4#&4{=l=jzckVOvS`84RKT;jzbW~EW|Mdaa16V'
        'qY%dw#Bm@dj#-Ff8sazzaa16V(-6l=h~rj>V;15#0&z@19Fq`71>(3H;<yXqxC7#tgE(%7IBtVDPR7J>4C0uDIA$P@X^3MA;y4I#'
        'Oh6nJh~p86V*%ng3voOQaeNu#cnIP+198kl91lVq4?rAWf;jGnIKBvR+y`;o3vpB-jyZ^98sb=jIF=xeC5U4Q;#h(>mLQHLh+_%j'
        'Sb{i~q&SwOIF_V1mZUhAq&SwOIF_V1mZUhAq&SwOIF_V1mZUhAq&SwOIF_V1mZUhAnm+#oj#R|)8lz0JNCXwJmgO`24}Mwar#}o='
        '$^(kRAGrLDTm0-IKgZw9^LhRj|2o(B+kAm91__t))<K~>l(b6i34?K{&&I@)U%Dj<-<;@5$NLw*F7lc_sC`iTpmsn_nUpGsRAVOC'
        '_jcr}k~g_kRJN;Y*bC^D*&K|e3%Vs%l}_;)(gyw)cz@-8du*2H|M<eGo&U4fg#Pcgx1x~Z^k?qAAoK;{NrEup=v7)R^qRWgOeo6A'
        'eWI!N?7dQ@(<_X=g7LTzge%K*{OM=yl|PD9p+9l=Iqh@0k<($IC1&n(XWIVy)ZKn-A!hGrD_PYW?d|=I^SPR54bL$w*Qm^hxt$5b'
        '^DCbU=00EfnLzzB^8FsD2T6x5hrv*^_aHW;+q(~8kXhe<2!oN%4n!D?MSBpGydR6D@4@Q}cJ%s(V$@af9;(`olX8#~=Tw*0?X2_u'
        'X_LI<Ny&fr5`X%vZHcXRYtubdu}vVhR2^oCmzJA~lGzufz9{uYsY{er7D+6aD|l!T53Oh5Ara#t8RH=d9unYTD8@quJY>K_HpYW|'
        'N00>%3Gk2w4@vMa4j$4m9wxv;20SFeLk>Jlf`=@4NX2;A8GA=C0Uom8VHi9lz{7s<pn`{8;2{Sdwt<In@Q?)$Y49)@<6#y&90Csq'
        '!NY#=uopb+1`j*ILk>JlgNI4*uoXOH!NUl6NP&kWcu>H@QSdMh9+tqveC!=T9z5j0LmE7^z(Wf>w7^44^3akzv?LEL$wN!>(2_i~'
        'Bo8ggLre0|l038|4=u?<OY+c?JhUVaEy+Vm@<2|xGduKY=+p3jPXkicq4rNL+RMo&?EH*(?ffi!{-|rGXZk62dZuGLJ>%HvS-3F3'
        'YvSv_PuG+lK+1G26$5fK_6j?mu5F0{xh0maDF8ABAje`rjsnOWfXv2TVNb-;wH*L*96+W3<nGujYzbr%K&k*T7faXD08#;vF9OJ2'
        '0CE~YjseKw7?6hm<bD9T8$jj&<RpO10?1VC74``LSpbkTv2<+@fZPEfrvc=649Ix^nTw@srvao2AQb?48$jL!kPQII0pyYda{jSb'
        '*m((LP6C+*kTf(wWaKqE-p!78yW`#Icy~MAy^eRk<2~qj52e>;Gx8*yV-<T<cW9MXVMX8Zh|;Cs5lUC;;@5t(Amg;06sMO>CKr<H'
        'cc`@3bBspxJG#d|(NDt6_Rsrt(-yz<X&A0J<JcY!N9$E_c+(Q-vjqDd?EAfrZ(6|1v(NO&EUho4JD=}n-rMYG+vICU+?lJ#<Mrli'
        'ha9~+bHu%RJoEmhWiF|DeDNODw8>HR3qN_PD2jn9+T`Z-<^6*stzPf1EDh4~{!hu?%lnm|iw%HZh_7FYuV0C;U(;7GA%CH;$x8mo'
        'FXB4KR(?x`MSrZ^Bd^zL`!|VbwLQ?!r~3I+Kc5o$)XLwJSZyziCn%wzucs#>`2-^5{!<!6C@~_^F(Q&NA_ijnPg_AmI!1&7BDTkf'
        'NP>uTZ2w6TkpdBuAYvev&?q2c5=10p`%f7Vu@6K{gNQVU*dHSz3nCN{u@^*a2N9z&A`XCvT_9o-M5IB)iP-+r-WU;EK}0I{o4lhS'
        'A`c=|5Rr=|G;;q*0TF2saTG)}K*W5Eh@XOpk7D~zr$K}&iBKdF4<!)~BoX%|5%(k!cO?;bBoVhI5jQ0f4M_x-L@Y@n<{$e_US1NB'
        'lUdAoqHDq32ci!|ABY}n?sfvmKjjlEKOCZ@>a%B0{ifFc3)uf6`QydTPTCx0escnA{>dUufu%t?1<niN=M$Y%9Vv*P5KU6}5AcOf'
        'AUQVx00'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
