# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/pi/ws/types/public_regulated_data_types/uavcan/pnp/8166.NodeIDAllocationData.1.0.dsdl
#
# Generated at:  2025-12-19 12:32:01.584395 UTC
# Is deprecated: no
# Fixed port ID: 8166
# Full name:     uavcan.pnp.NodeIDAllocationData
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.node

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class NodeIDAllocationData_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 unique_id_hash:    None | int | _np_.uint64 = None,
                 allocated_node_id: None | _NDArray_[_np_.object_] | list[uavcan.node.ID_1_0] = None) -> None:
        """
        uavcan.pnp.NodeIDAllocationData.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param unique_id_hash:    truncated uint48 unique_id_hash
        :param allocated_node_id: uavcan.node.ID.1.0[<=1] allocated_node_id
        """
        self._unique_id_hash:    int
        self._allocated_node_id: _NDArray_[_np_.object_]

        self.unique_id_hash = unique_id_hash if unique_id_hash is not None else 0  # type: ignore

        if allocated_node_id is None:
            self.allocated_node_id = _np_.array([], _np_.object_)
        else:
            if isinstance(allocated_node_id, _np_.ndarray) and allocated_node_id.dtype == _np_.object_ and allocated_node_id.ndim == 1 and allocated_node_id.size <= 1:  # type: ignore
                # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
                self._allocated_node_id = allocated_node_id
            else:
                # Last resort, slow construction of a new array. New memory may be allocated.
                allocated_node_id = _np_.array(allocated_node_id, _np_.object_).flatten()
                if not allocated_node_id.size <= 1:  # Length cannot be checked before casting and flattening
                    raise ValueError(f'allocated_node_id: invalid array length: not {allocated_node_id.size} <= 1')
                self._allocated_node_id = allocated_node_id
            assert isinstance(self._allocated_node_id, _np_.ndarray)
            assert self._allocated_node_id.dtype == _np_.object_  # type: ignore
            assert self._allocated_node_id.ndim == 1
            assert len(self._allocated_node_id) <= 1

    @property
    def unique_id_hash(self) -> int:
        """
        truncated uint48 unique_id_hash
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._unique_id_hash

    @unique_id_hash.setter
    def unique_id_hash(self, x: int | _np_.uint64) -> None:
        """Raises ValueError if the value is outside of the permitted range, regardless of the cast mode."""
        x = int(x)
        if 0 <= x <= 281474976710655:
            self._unique_id_hash = x
        else:
            raise ValueError(f'unique_id_hash: value {x} is not in [0, 281474976710655]')

    @property
    def allocated_node_id(self) -> _NDArray_[_np_.object_]:
        """
        uavcan.node.ID.1.0[<=1] allocated_node_id
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._allocated_node_id

    @allocated_node_id.setter
    def allocated_node_id(self, x: _NDArray_[_np_.object_] | list[uavcan.node.ID_1_0]) -> None:
        if isinstance(x, _np_.ndarray) and x.dtype == _np_.object_ and x.ndim == 1 and x.size <= 1:  # type: ignore
            # Fast binding if the source array has the same type and dimensionality. Beware of the shared reference.
            self._allocated_node_id = x
        else:
            # Last resort, slow construction of a new array. New memory may be allocated.
            x = _np_.array(x, _np_.object_).flatten()
            if not x.size <= 1:  # Length cannot be checked before casting and flattening
                raise ValueError(f'allocated_node_id: invalid array length: not {x.size} <= 1')
            self._allocated_node_id = x
        assert isinstance(self._allocated_node_id, _np_.ndarray)
        assert self._allocated_node_id.dtype == _np_.object_  # type: ignore
        assert self._allocated_node_id.ndim == 1
        assert len(self._allocated_node_id) <= 1

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.add_aligned_unsigned(self.unique_id_hash, 48)
        _ser_.pad_to_alignment(8)
        # Variable-length array: length field byte-aligned: True; all elements byte-aligned: True.
        assert len(self.allocated_node_id) <= 1, 'self.allocated_node_id: uavcan.node.ID.1.0[<=1]'
        _ser_.add_aligned_u8(len(self.allocated_node_id))
        for _elem0_ in self.allocated_node_id:
            _ser_.pad_to_alignment(8)
            _elem0_._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        _ser_.pad_to_alignment(8)
        assert 56 <= (_ser_.current_bit_length - _base_offset_) <= 72, \
            'Bad serialization of uavcan.pnp.NodeIDAllocationData.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> NodeIDAllocationData_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "unique_id_hash"
        _f0_ = _des_.fetch_aligned_unsigned(48)
        # Temporary _f1_ holds the value of "allocated_node_id"
        _des_.pad_to_alignment(8)
        # Length field byte-aligned: True; all elements byte-aligned: True.
        _len0_ = _des_.fetch_aligned_u8()
        assert _len0_ >= 0
        if _len0_ > 1:
            raise _des_.FormatError(f'Variable array length prefix {_len0_} > 1')
        _f1_ = _np_.empty(_len0_, _np_.object_)  # type: ignore
        for _i0_ in range(_len0_):
            _des_.pad_to_alignment(8)
            _e0_ = uavcan.node.ID_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            _f1_[_i0_] = _e0_
        assert len(_f1_) <= 1, 'uavcan.node.ID.1.0[<=1]'
        _des_.pad_to_alignment(8)
        self = NodeIDAllocationData_1_0(
            unique_id_hash=_f0_,
            allocated_node_id=_f1_)
        _des_.pad_to_alignment(8)
        assert 56 <= (_des_.consumed_bit_length - _base_offset_) <= 72, \
            'Bad deserialization of uavcan.pnp.NodeIDAllocationData.1.0'
        assert isinstance(self, NodeIDAllocationData_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'unique_id_hash=%s' % self.unique_id_hash,
            'allocated_node_id=%s' % _np_.array2string(self.allocated_node_id, separator=',', edgeitems=10, threshold=100, max_line_width=1000000),
        ])
        return f'uavcan.pnp.NodeIDAllocationData.1.0({_o_0_})'

    _FIXED_PORT_ID_ = 8166
    _EXTENT_BYTES_ = 9

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8!9_)B0{^X9-H#l_5%2Tod2Ni14K^6;#(ek=_7<Npwz18}`Oc0{i;ZO)L!_Y1>`w3XgxTrI^vvBY5mI<agr${o5)+9(fj@z_'
        'yz<0jM5H`N{0Tg!s=KCk_C696#S&EAOiy=p)vtbC)%(XifBnO0;r@-zq{GmLajRoh76ozidC-kjtJ5=s)YvFj<>-kAc~<oDB2y2C'
        'sVcuNXTL1JC}&1{J4rBr_h*V=wHG9<G)Y@`O{kWa7UJ0Sf;=+GQjiDbXu7kiG7Eo}T8#ETBK_;KJ=GR}F25{C2RlKYXHmDvl`TJo'
        'xp%ONN0p<!w;~mXV{00n5Z3DCXyQ(vr&%<J@@N%C9Q!D-(MqDi<s?@tDx2Ke!A>{IJF!Yua$UC1!{oid=A8lTuGGgz&)lmf!p~ZZ'
        '@a_)2!X5poykCxvcWfRcVUUIOi5?eSy?1oDNTS~tsuP7B9avqC_H;tiD@WHC5*cJLJPWd+ym(~}REZ;`>C0Rz>A#y>UaB6TlVh2{'
        '%B>QnKH`nn$3~}i@LrY$!*X=uQ2<Zj$p_A?1$;WW{U<sqRs)sf-ko|E&5XwTSi41+mrA`~AE=_J4}DsWjnL1K_H6rzeojB%7U&s$'
        '<}2rfy{kc7z|1d>1ehL-j@1Cr=?*=zz9{u&J#Qfzp-M9ah*DwscyzeakJeS#Nlli67t6b&qaACCtf$~btU74`z8>vI5l7u}bl@HU'
        'dHo(f{Tenm^#-_H8$|A|G=l%FSwItR6y&M2=*Cg6lc|*=#`VUig17tp?%{jfKfrc*sWsm^-$G}XIR^e1#uO~b(0Snf)u^Y+$FR-6'
        'EvbH#C@TXOFo<HS@epD-2-c%PF_7SoD3s1CGO`jjtdbBWktU(whboJQQL-WdAc@7z%QzUStkrmgUs-^|n#y2skjVK9R{%>&2Ju=j'
        'v^06&Wbhy!e{Wlj`>K!M7`KK^RWIsCK6Bmhfq_Y)q;Fc~=!gr7Cx!$p^NG6ICA$C=YIMQ{p_7|VW=!rrv}pjY(C^Ra1${#=>Lq<s'
        '-_pNwUfa{@#^BypE7*>627H)r{<|C<x)J3bybs_{g6(K`$E4**?lg%V4!Q<n3qiW01_qJ>xA|eJvLH9v82tM>JsknF=ubya-V4GI'
        'T)t(H?&90KMI1w}Zhi|hcy#}zoM|7~uwCH4)K65lr;9FZcMv6I`v@w*Ix72-S^#i3cY6xI6C3SaBzL2n+Gy{gzxUGL`%v!LXzxe4'
        'Yok3)?+>8dztL`>+_%v_h;r{n`w)$P0_E<F_F?+&Nt*8neSg&3-F}MXF_OngK27o&k|#)>B>61K=SZF+`8>%NNS-EnhNL9<BFVEP'
        'Un2Q3$yZ3eO7a}Z8IrRkUnBWC$tKA;k}Z;NkUURvp5z6RZ<4%7@-32=NM0s+h2+~Luadk*@;b?PNWM$*J(BN}yiM{GlA7c?$*)L$'
        'L-Jda-;w;D<c}nOBKfnIcc!OEIaw()m2#z0Zdb}Dm7*(Uy;8oaly55K+e-PaQogU0A1mdjO8J?T0!~-8o&qOfQ9#eSwhM`J0FGUt'
        'jVK?&!8&@XO6NYF{B$&pPnl^rWlsC^<&plid#rz>JGF#;deJ0!h$P!)KCXs|57dp!rnR5qGqh+LvUp;u6ZeB;McoIM&ZC`Z<TIb$'
        'Q}DrW!KkDyw1KlQ#T>74b=zDQTe4knz6;KHfw_CYYgM)j&Ue8XFF5A~XT9LO7h5u4aPAAve!=-Km;nTHfM6C7%mad%Krj~wW&^=|'
        'Aea#ZbAn)25X=jLnL#i&2xbSt{2-Vi1apL7mJrMnf|)`vR|sYc!F(Z@F$8mlVAc@K8-kfbFn0)M55fE)m_Y<{h+q~G%p-!CL@<{K'
        'W)s1DBA8JGbBbVA5zH&775WEOyUHRYrvZ{De-R{iZGz-(gw;NN=O8(S0CSL>Mj$r4wuc}&jpGh^O%Nof+Xo4f)9nU9a=LwhAUREt'
        'oJN2@#q%EX+FpXBTj6Q1?IuXNwN7|#iXiD$eb#Fy36f4b#oF_%y};UO*3PgdS$mPSv#h<u+RLoH!rH5>onvi=wOQ6)W9@a;nyk&S'
        ')?)1q*3Ppw&)Nmn-em0}Yj3f3iM7kDU19BQ)~>R4jkW8ny~EnOti8wD`;|tJbgJWg=nakrzI}w^8*54|@u7hJ;DN^CwX38Wr1=o4'
        'Qkf~}hiopPxU|8Ff^wF}q$c(CyB`PTZerDVAoLtczl~%r_0iwOQ$pyM3VrRdzJBLlXY@N;s?^bLXl~2V*(>vxE^XW6PPPI111R}F'
        'dF!wc549`iq4amhMAf+k{BdOy7X1;lqEP1hO1%Jk*P>k4%5}M>6&Cf0NrnScSpNzNc<YM&7<*C`HlUinEW1PKq;R=37{(?Do6;6N'
        'EdwhT<G|XeCl?p)wj{P7HS@rT9(0Kj*kGV#m;KBPoWUlGR-y#D&5sry!H077{A9P#aHd-5s-R~G`LS)uTd<ef77WZrO-juWIip%D'
        't)^3NErG4BZ*5AI_gb@PK;|42xQ3*$q7pc5;k9c|utb1nw!V$+A|zKYK#1Ii?<MzSnwi}6Oe~|^s<`iaF580^)MExW4Q+XWU9jIF'
        '1_ht4UZ^ca9;^?<saGQmqcgi(Kuuv~ky0Z^#)H{b!A1?BGYHWkx$H+7pgD~dylOREd)S8-1G_nQ88E&8fR5{2jyMl`(2s$~E2sz3'
        'LYon*xqb#cR}Cr^%qqzE_|`&zwlwlhaJ7(>P~c!!?u?%>2kdZBhcyQPXqax(rA3r`_tYQ5{HB`+&<clu(MFJ_zNroBmmh9qzesw{'
        '2<lG9yLZkqMV=M_C{WR1Ijkaa6<8NrcE56_&^<n>aMA`(8u<-X*EDkR{^H!Fiyz;l95YEgq&t>1H8FYarnN<!yQG6O4Ix&9HIrFy'
        'oh?$=p>Iuemz0np5Cd%Q>0-=Et4$GyasaMD_n=obED+YG$Q{tBkH_ZS@t?(Qs%RC)u10~!=sXA9bXOw)0Bk2TGBLUA8NUF>lO21l'
        '&P|3`rRG9pmRR-kxzAN*=28b+<%2&NW8k?g^!Exr*sz<ksZ|A-z^k2YLeN9Ua}IWN_u&j{Y}s^x**}J(tg;cZr?!KZT+T7HX!J@F'
        'eXc08+yX%P0r(;V)PljF19zwl&1+c5SE(Q-z1)tO((TTr5gka1wu68jhmen}>So7prMkqy!LW@r9l@*=?gjy=M*aw-Ca?t>tA@_?'
        '5GgbaL695BFL#T_SW}9yHVB3?QErelt`AXLvKx#vV28_B9j)lOI}bmq(=yJ{)5c&h4BFD548Ris%z&XTWd|zPCPWC=B80JUwpuv9'
        'dP5gh8x7K!&jGM{xdsZ0zIPWw97hCB(`jjjcT!o+oi3mQg8=6PiOznX=364rfKQl)3F}oA(3Bc-8vJw3Zx7EEX#CWwV<gxiIK^!c'
        '3{KH_0GR7Iy|-aFW>LMsXw(dH5yaK&1xS5)v=~=K_f!$AzjvWPW|srtn23nHqU~nG<H#A^Q>jl5;QZcr2A{VUp$YpLr*o4q=(8H{'
        'H#6ri>l4wPvVA;JD*(DIT=T%fG_5|`e3n3Xg7LB5Rfu>hM)1>}4<YN)dJJb+6Oi&@Qs*J1&H*`MetK|J$2Of)F2gfZtY}YY22Dl-'
        'ta5an6|u5c8x1M%gC-YR5~g>@o4Xgs_+EvVQqE68Njb7{^?>y!P{j7P+y@u7e2@p2N@xZ#vwRp0R92mmu;~!ci&b6*41v}?tYFLr'
        '-f#x0^)$+Ydc`<7<BVGi4+lUR{Oxur7n<@$6S7P$&hnlnzXOPPBmcWeat8PSKm_4aYqL9Sxtl?0i9d~4cYu#6VN+?|q+`{E2y@9}'
        'betrx4<9<~Er)-TKa=2-Ik5Pb{4T=wwW_(cbQCa`ZzE<Vl6iI<h(#BOAQ^6RhC^Yx3Z9AjRL*+$2QgH0gCOte|G)PutCq;B?K+5$'
        'Z{NIs6QJRK3aOJP<lh`8VN*se1*LYC%o9QL1TtH>?LYlnxVr@ZpW%pZj+b);m5udOzPP!T#nJ!Uid&;vC*GZMz~&~kJK&j#0St%6'
        'fSu?YF<($prG-blpXJTXvp_fp&@AON2@y$J6|>vagnpunEqQYtisn+^o%m_RH=oD1{cTn02iyLpvi%)s$lCbXKm4$N;+^MqBkT8|'
        '=kXqNfInjBq<vl+_%DTbKiq`}fA=>^SK#UG@zZMX<YVmgTmJ@Rl3W>v9smF'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
