# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2024-06-20 11:16:14.354354 UTC
# Namespace:     uavcan.si.unit.velocity

from uavcan.si.unit.velocity.Scalar_1_0 import Scalar_1_0 as Scalar_1_0
from uavcan.si.unit.velocity.Vector3_1_0 import Vector3_1_0 as Vector3_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
Vector3_1 = Vector3_1_0
