# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2024-06-20 11:16:14.431133 UTC
# Namespace:     uavcan.si.unit.frequency

from uavcan.si.unit.frequency.Scalar_1_0 import Scalar_1_0 as Scalar_1_0

# Convenience aliases of the newest minor versions known at the time of code generation.
Scalar_1 = Scalar_1_0
