# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /Users/igor/Work/misc/cyphal_ws/types/public_regulated_data_types/uavcan/node/port/7510.List.1.0.dsdl
#
# Generated at:  2025-12-16 13:33:59.293170 UTC
# Is deprecated: no
# Fixed port ID: 7510
# Full name:     uavcan.node.port.List
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations
from nunavut_support import Serializer as _Serializer_, Deserializer as _Deserializer_, API_VERSION as _NSAPIV_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.node.port

if _NSAPIV_[0] != 1:
    raise RuntimeError(
        f"Incompatible Nunavut support API version: support { _NSAPIV_ }, package (1, 0, 0)"
    )

def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))

# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class List_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    MAX_PUBLICATION_PERIOD: int = 10

    def __init__(self,
                 publishers:  None | uavcan.node.port.SubjectIDList_1_0 = None,
                 subscribers: None | uavcan.node.port.SubjectIDList_1_0 = None,
                 clients:     None | uavcan.node.port.ServiceIDList_1_0 = None,
                 servers:     None | uavcan.node.port.ServiceIDList_1_0 = None) -> None:
        """
        uavcan.node.port.List.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param publishers:  uavcan.node.port.SubjectIDList.1.0 publishers
        :param subscribers: uavcan.node.port.SubjectIDList.1.0 subscribers
        :param clients:     uavcan.node.port.ServiceIDList.1.0 clients
        :param servers:     uavcan.node.port.ServiceIDList.1.0 servers
        """
        self._publishers:  uavcan.node.port.SubjectIDList_1_0
        self._subscribers: uavcan.node.port.SubjectIDList_1_0
        self._clients:     uavcan.node.port.ServiceIDList_1_0
        self._servers:     uavcan.node.port.ServiceIDList_1_0

        if publishers is None:
            self.publishers = uavcan.node.port.SubjectIDList_1_0()
        elif isinstance(publishers, uavcan.node.port.SubjectIDList_1_0):
            self.publishers = publishers
        else:
            raise ValueError(f'publishers: expected uavcan.node.port.SubjectIDList_1_0 '
                             f'got {type(publishers).__name__}')

        if subscribers is None:
            self.subscribers = uavcan.node.port.SubjectIDList_1_0()
        elif isinstance(subscribers, uavcan.node.port.SubjectIDList_1_0):
            self.subscribers = subscribers
        else:
            raise ValueError(f'subscribers: expected uavcan.node.port.SubjectIDList_1_0 '
                             f'got {type(subscribers).__name__}')

        if clients is None:
            self.clients = uavcan.node.port.ServiceIDList_1_0()
        elif isinstance(clients, uavcan.node.port.ServiceIDList_1_0):
            self.clients = clients
        else:
            raise ValueError(f'clients: expected uavcan.node.port.ServiceIDList_1_0 '
                             f'got {type(clients).__name__}')

        if servers is None:
            self.servers = uavcan.node.port.ServiceIDList_1_0()
        elif isinstance(servers, uavcan.node.port.ServiceIDList_1_0):
            self.servers = servers
        else:
            raise ValueError(f'servers: expected uavcan.node.port.ServiceIDList_1_0 '
                             f'got {type(servers).__name__}')

    @property
    def publishers(self) -> uavcan.node.port.SubjectIDList_1_0:
        """
        uavcan.node.port.SubjectIDList.1.0 publishers
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._publishers

    @publishers.setter
    def publishers(self, x: uavcan.node.port.SubjectIDList_1_0) -> None:
        if isinstance(x, uavcan.node.port.SubjectIDList_1_0):
            self._publishers = x
        else:
            raise ValueError(f'publishers: expected uavcan.node.port.SubjectIDList_1_0 got {type(x).__name__}')

    @property
    def subscribers(self) -> uavcan.node.port.SubjectIDList_1_0:
        """
        uavcan.node.port.SubjectIDList.1.0 subscribers
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._subscribers

    @subscribers.setter
    def subscribers(self, x: uavcan.node.port.SubjectIDList_1_0) -> None:
        if isinstance(x, uavcan.node.port.SubjectIDList_1_0):
            self._subscribers = x
        else:
            raise ValueError(f'subscribers: expected uavcan.node.port.SubjectIDList_1_0 got {type(x).__name__}')

    @property
    def clients(self) -> uavcan.node.port.ServiceIDList_1_0:
        """
        uavcan.node.port.ServiceIDList.1.0 clients
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._clients

    @clients.setter
    def clients(self, x: uavcan.node.port.ServiceIDList_1_0) -> None:
        if isinstance(x, uavcan.node.port.ServiceIDList_1_0):
            self._clients = x
        else:
            raise ValueError(f'clients: expected uavcan.node.port.ServiceIDList_1_0 got {type(x).__name__}')

    @property
    def servers(self) -> uavcan.node.port.ServiceIDList_1_0:
        """
        uavcan.node.port.ServiceIDList.1.0 servers
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._servers

    @servers.setter
    def servers(self, x: uavcan.node.port.ServiceIDList_1_0) -> None:
        if isinstance(x, uavcan.node.port.ServiceIDList_1_0):
            self._servers = x
        else:
            raise ValueError(f'servers: expected uavcan.node.port.ServiceIDList_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Serializer_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        # Delimited serialization of uavcan.node.port.SubjectIDList.1.0, extent 32776, max bit length 8200
        _nested_ = _ser_.fork_bytes(1029)  # Also includes the length of the delimiter header.
        _nested_.skip_bits(32)  # Leave space for the delimiter header.
        assert _nested_.current_bit_length == 32
        self.publishers._serialize_(_nested_)
        _nested_length_ = _nested_.current_bit_length - 32
        del _nested_
        assert 8 <= _nested_length_ <= 8200
        assert _nested_length_ % 8 == 0
        _ser_.add_aligned_u32(_nested_length_ // 8)  # Jump back and serialize the delimiter header.
        _ser_.skip_bits(_nested_length_)             # Return to the current offset.
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        # Delimited serialization of uavcan.node.port.SubjectIDList.1.0, extent 32776, max bit length 8200
        _nested_ = _ser_.fork_bytes(1029)  # Also includes the length of the delimiter header.
        _nested_.skip_bits(32)  # Leave space for the delimiter header.
        assert _nested_.current_bit_length == 32
        self.subscribers._serialize_(_nested_)
        _nested_length_ = _nested_.current_bit_length - 32
        del _nested_
        assert 8 <= _nested_length_ <= 8200
        assert _nested_length_ % 8 == 0
        _ser_.add_aligned_u32(_nested_length_ // 8)  # Jump back and serialize the delimiter header.
        _ser_.skip_bits(_nested_length_)             # Return to the current offset.
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        # Delimited serialization of uavcan.node.port.ServiceIDList.1.0, fixed bit length 512 (64 bytes)
        _ser_.add_aligned_u32(64)  # Delimiter header is constant in this case.
        _ser_base_offset_ = _ser_.current_bit_length
        self.clients._serialize_(_ser_)
        assert _ser_.current_bit_length - _ser_base_offset_ == 512
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        # Delimited serialization of uavcan.node.port.ServiceIDList.1.0, fixed bit length 512 (64 bytes)
        _ser_.add_aligned_u32(64)  # Delimiter header is constant in this case.
        _ser_base_offset_ = _ser_.current_bit_length
        self.servers._serialize_(_ser_)
        assert _ser_.current_bit_length - _ser_base_offset_ == 512
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 128 <= (_ser_.current_bit_length - _base_offset_) <= 67728, \
            'Bad serialization of uavcan.node.port.List.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Deserializer_) -> List_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "publishers"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of uavcan.node.port.SubjectIDList.1.0, extent 32776
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f0_ = uavcan.node.port.SubjectIDList_1_0._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "subscribers"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of uavcan.node.port.SubjectIDList.1.0, extent 32776
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f1_ = uavcan.node.port.SubjectIDList_1_0._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f2_ holds the value of "clients"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of uavcan.node.port.ServiceIDList.1.0, extent 1024
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f2_ = uavcan.node.port.ServiceIDList_1_0._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f3_ holds the value of "servers"
        _des_.pad_to_alignment(8)
        # Delimited deserialization of uavcan.node.port.ServiceIDList.1.0, extent 1024
        _dh_ = _des_.fetch_aligned_u32()  # Read the delimiter header.
        if _dh_ * 8 > _des_.remaining_bit_length:
            raise _des_.FormatError(f'Delimiter header specifies {_dh_ * 8} bits, '
                                    f'but the remaining length is only {_des_.remaining_bit_length} bits')
        _nested_ = _des_.fork_bytes(_dh_)
        _des_.skip_bits(_dh_ * 8)
        _f3_ = uavcan.node.port.ServiceIDList_1_0._deserialize_(_nested_)
        del _nested_
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = List_1_0(
            publishers=_f0_,
            subscribers=_f1_,
            clients=_f2_,
            servers=_f3_)
        _des_.pad_to_alignment(8)
        assert 128 <= (_des_.consumed_bit_length - _base_offset_) <= 67728, \
            'Bad deserialization of uavcan.node.port.List.1.0'
        assert isinstance(self, List_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'publishers=%s' % self.publishers,
            'subscribers=%s' % self.subscribers,
            'clients=%s' % self.clients,
            'servers=%s' % self.servers,
        ])
        return f'uavcan.node.port.List.1.0({_o_0_})'

    _FIXED_PORT_ID_ = 7510
    _EXTENT_BYTES_ = 8466

    # The big, scary blog of opaque data below contains a serialized PyDSDL object with the metadata of the
    # DSDL type this class is generated from. It is needed for reflection and runtime introspection.
    # Eventually we should replace this with ad-hoc constants such that no blob is needed and the generated code
    # is not dependent on PyDSDL.
    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8$6rBd0{_KX-ESOM6~Es2W9-C<6E{vto92doIc>a~(54@urE!u5%*L^mZ>Y+2cIJBT-OSD`b7$;qMZp!K)Y3?`)TzV^<$?cz'
        '2M~w{gm{EM0|^NU@r2-oaL%2xpWbyqG;O5pnVI`_?z!ju&hK1rj(+m96U_Wek2jj0_WYu)MWh^Gz3WtbQMBE#-UzjdMV3xqkE6tm'
        'lStfXHbnMucJlq~y=*=mvje9N?S~U*-F1Ru5PG862&1@oMd>(8Eqh%=T7^L-Svqlxo<GjYBW3nM_I{S`wVgPQR3(Xp&fbO@hv?Go'
        'm8D~smGHfe4pX-0#Eu=KVzA2eCE=?&Xzlf?I&P~V5D|8nycvKRJ<W0~ePYKRt|yh6aO0&*W;1d^PPX)x`#@JYLt|&t$A)MfMNTtI'
        'AGxgV3Ga#ss<B+ePraH=+rk%h5ybf(hMAxd;kMK|^w@hL41MABZUJmrQL*itWx&E<7}wFUU5EW-@?<)<+L{1|6)!^DGB&|!upedD'
        'Kuuf6PT)C_*FDizQb{LariSCHxS1_8o{riTUuWqvEj>HELFKsrJxljpP;tKd>+nkYrhDwLk)?dtB)VCzguZgKbaq+PL$E>&hqlrX'
        'krRhe_qn=Kfj`LC(?i!pL&R!uzk+=im6sQw<AJM*?>kYmzZXol?)ZtwKFa3HBip(HdmpvyDxhuGoqOhK0*#vZ4h$)eU|+Va!QA3r'
        '!wHOsUrj1F7`$q<?&!N2jP*j;%AFfha20ss9*;yL5*kij^B6yR@Tk_5h`3Rq$Ztf6;0p_!x|I?wyduBs_}YASD*4yIe9vI9wmZrv'
        '(<8SW@E!1*VO}TaWufi*M~A!qZf*}wHG2~_Tn&V`6vUz`qTV%%<!M=xFUS|Sj4j4;<I0;ULw)zB*2OSDpNl&~X64%8!F!e$@4!%5'
        'lULGXEvEsCgLTm4J@H{(GtT1pt$AV0<XYso_!T_Yx=hc|zI^|9dE^7|e>^ae&UOKkU1{d{hUzHk%J0g00%7Li(YX#lOtzKox7RSb'
        'Z8V#$yzFXv(AHrRxdIw|VK*EIqI5qBUsZ~>AG)AdI=KqadT$jQKh9E7x(UIqOR5@1rQ2b2w^Uc!ExFBxbbNb5mk=3rsgYD5BJ4<1'
        '!TDhM4)W<zeuO1F!V>CIY9C?oO!0IP?Uk7@pS7i<L9GZ82UcBIuE@6FP+p-C3owMEqef0p6`Dg&?uj)8r_3u&<E^?OTyR#`n7Npx'
        'GsaGN#t6`-4VI7RI)V42Rv=I>*m}pgM0&&+$c{rh3d7h;qXBBbOMaMs<Fm4g*|>a3zM4D3Yw`{9F#`sxj_0YMx&tzxb&0$OV|*I$'
        '01{dw@12z`aLcRZ8My-gSKmXx$dRC2Ah{<;k@6_LkJ0-$%F*re1j@p8*`oGIloQ+KDU{>e<-I7!w#)md|1`=y+vWW<?f}g<L*oyk'
        'oY^iPA~{R)5t4^V&XGJq@==msB6*bLV<aCZd5q)}B#)EiBu|k1GRY@NK1K3rlFyKQmgGFilO&%b`8>%}Bo{~)NtQ^SCV7VBS4h4<'
        '@<ozoNxnq#Ws<Lue3j%ml3ykH8p+p5evRZCB+utEk=N-V$NsbB`{|)pN?SwDLL8+7a25dEnevG7&KEy~F+*JRFyJKOO)xMAVtU3D'
        '2my^@*W<JnIBm~VN3LN|@0KXX?Ykz?mG8rVPmGf@xw8EC1L)-~XVvmL<T#<R)q>W44rrwexEJC%(!%x)iMp9OiyR+$xYm{QFbO&_'
        'hgjtm!7-&ln$)pyJnV;%gL#yzHC_+%vAsz%N2!6yu#@KID9yDqMe)sg12|28ij&_1^L>9y{@|+I1Q>EYGjMJ%Trvyy0<-+_mPv10'
        'J<vJXmDa{`b%p%sa{|Yo3<N@kKJ_W#AGikmAC7;l5C0h9A0zx@efY-+{}|yPBm858e~j>t5&p40{9}ZFjPQ>U{xQNoM)=1F{}|yP'
        'Bm858e~j>t5&kj4KSub+2>%%2A0zx@gnx|ij}iVc!aqj%#|Zxz;U6RXV}yT<@Q)GxF~UDa_{RwU7~vly{9}ZFjPQ>U{xQNoM)=1F'
        '{}|yPBm858e~j>t5&kj4KSub+2>%%2A8X+s+ipkxSRBT{bs*-?E#{QL@gc;up}>Yb1l2t59pB#(%ql<}Fv08(Acr$KIsDM9WL;cb'
        'UA(w-<6FcKWla7mo50t*_#KA!yu2Y#$bZY*weO5DR%7_%;m<qplXL~XdYG&XYsvutaOYJ}qJxk+@7`^k;#8ZPb@c$!#+Bw!)l|hP'
        'u0yaLTG!!*oi1qguHaB&85G?J6W;?sy(_@_FbGxUo>~J!m-sP{LoT5X^kMp73h1>VvkNX#^~f<SP&WaZ>l#>M$bk+a1vlq-if;(0'
        'SHg8rm&Y3+7x!QY4;zMep95{QsyATbb*fGl^7Lr7duj?6#V*~BV!VUAMNpCu>mq9Q?YreHedyUsJg0jL`iFs|=>a=-s=K87Kkt(0'
        'J8;|i_Sd}I-yWFQr_H5Ce>%?xo|k{A9R|P3^EGC3D1-sC`;xfT`PjzyzVCTt%VUr-kLT6k35X-sik|-|zG^jiZ##ai4sT!h@l8NU'
        '2|O##maWZn4l2F;E-A7lP!SOQN6H^?q{EJn_a5Ir=;>d}BQt&3)-u-+bZpk<FcQY0b$)Xw37awo&=O2#AhL%c%^8*keO)Mg2lhBj'
        'Pmgx7sR8$8c`^Cm`!e}-`x4^$wkbzC)&ALKRv2v0OZ4=0?9pqe5i%6Etl-aZQc~z6B?TfS1tKLQeWb)9Qc@sNGESt#B2qF&q{Jdp'
        'Qs^Tk1tKLDk&;71O7;;cv51t66Db)dQeqJ)*+-=05RsCjL`p0oC9_0I3VlUci<BHBQc@sNGDoDuB2sdkNXa20C1XTNIFXV^h?H1F'
        'N}eTB@;H%_gG5TkiIhA?q=XYGnIlrNk4Q;@NXaQ8B~KD5IZCADAdwP_NXaWiN=_3gnI}@hiIhCrSCm<Oqy)TSyYEI0NXbLJjQjs6'
        'OQD~#)D9N_K>vU!`WQYPDSQr8r8}GlP?hu-T|6c4+s{)lGXtCBairEwPN)06K0cy=0_d;~tVZBO$T08@2(vn|fNsK*FV#-`ZX}?O'
        'HwB%6?Iid|3YceI;jLh+Py|jAhi>RUkRbFR*cVV})&7WCkdkjVl68T3?RVH`qV{_f2&}nZpiBH$&Qd#3=+3)O6&{#(AG%d)KLur%'
        '*=X%k+|$ELujS3%vMU?iExYp3q1ko9^_98x>`$Dv-{O9tgK_IlW*vkMRyR7#Eic}&S8rapvUG9r#?s1Fd-ct0ODmTUwl?0<0^-Qi'
        'Z%-|ecf&DZXsxMg5}7L^jEo?RdD8IE>KI6d={xl>3G(X`RfjqON8?#@Elo{8EFte)2U_ny%sD}G!)X??9*ina?SQCX;$9EdevN+j'
        'EBv{Q&i5O9`Zhk@!5<rc-fBDK@~vYAzaGW~_{(R{oGuP4v;I`*F0-&dRTpOK#wH+55p`~AffM!AEeo}-!drdkH>3b#MjZIJ3b9=A'
        '{U#41D32Co=$<Tg&#`lzHu>_f`kHq*?#mCWRhSVc;hv}@<}I(?V8^sXdn69TGMeflZI-;Yda;F<+JJ9T-=VoGisGp@fRiWh98G22'
        '?xV@gVf54@=z?8z%ePGBhkxeGhvQ!qE6P`K6E$xYje&r&F}e#58%H5lg2tP%F!YpD4MH6&w=-0UR+ee`Dy;?P=p0mD38Sl<TDZG%'
        'bTnTJeLvjLc*u*f>9w+o5w~~+lu}`Y3i?oT`Wz0;hg8!lKnF)Cr{F9Om=8|!`jwU2{qth_g8&^epR)$#$1Y*+N=%I212Ws_7nRV4'
        'fc59pv-b0@blO!T8SplZIliBlE8kp&LUm{TyQ8Icsn8nr4zx8!2aVd%(lu%m+P1Ahqjt0)xEB8dA(u7Zsv!UX'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
